spring.application.name=controlesaidaescolar

senha.padrao=senhaPadrao
senha.master=senhaMaster
cors.frontend.origin=http://localhost:4200
jwt.secret=a4f25ce3d59e5c00d09a2d31fcb6d1a78391c6e4ea85b82b8a1f2147f12783a0x
jwt.expiration=720

app.upload.dir=uploads/fotos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# 1. Conexão com o Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/controle_saida_escolar?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configurações do Hibernate (JPA)
# 'update' altera o banco conforme suas classes @Entity (bom para dev)
# 'validate' apenas confere se o banco bate com o código (ideal para prod)
spring.jpa.hibernate.ddl-auto=update

# Dialeto específico para o MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 3. Logs e Debug (Para ver o SQL no console)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# 4. Pool de Conexões (HikariCP - Padrão do Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000